$schema: "http://json-schema.org/draft-04/schema#"

description: alignment pipeline configuration file

type: object

properties:
    fastqs:
        type: string
        description: filepath to TSV file with patient column
    comparison:
        type: string
        description: filepath to TSV file with rfcaller comparisons
    fasta:
        type: string
        description: filepath to index fasta
    dbsnp:
        type: string
        description: filepath to known SNP database in VCF format
    PL:
        type: string
        default: ILLUMINA-NOVASEQ-6000
        description: Name of sequencing platform
    CN:
        type: string    
        default: MACROGEN
        description: Platform Center
    pon: 
        type: string
        default: hg38
        description: Sample ID
    ploidy:
        type: string
        default: GRCh38
        description: Sample ID
    threads:
        type: number
        default: 20
        description: Number of threads to use in the BWA-mem step
    other_threads:
        type: integer
        default: 4
        description: Number of threads to use in small steps (split, indel realignment...). Few recommended.
    memory:
        type: integer
        default: 8
        description: Max memory RAM allowed in Gb

required:
    - input
    - comparison
    - fasta
    - dbsnp
