$schema: "http://json-schema.org/draft-04/schema#"

description: alignment pipeline configuration file

type: object

properties:
    input:
        type: string
        description: filepath to TSV file with patient column
    idx:
        type: string
        description: filepath to index fasta
    dbsnp:
        type: string
        description: filepath to known SNP database in VCF format
    PL:
        type: string
        default: ILLUMINA-NOVASEQ-6000
        description: Name of sequencing platform
    CN:
        type: string    
        default: MACROGEN
        description: Platform Center
    bwa_threads:
        type: number
        default: 20
        description: Number of threads to use in the BWA-mem step
    sort_threads:
        type: integer
        default: 20
        description: Number of threads to use in the sorting step
    other_threads:
        type: integer
        default: 4
        description: Number of threads to use in small steps (split, indel realignment...). Few recommended.
    memory:
        type: integer
        default: 80000
        description: Max memory RAM allowed in Mb
    outdir: 
        type: string
        default: bams
        description: Name for the output directory that will be created. 

required:
    - input
    - idx
